package com.example.rag.service;

import com.example.rag.model.Document;
import com.example.rag.store.InMemoryVectorStore;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.embedding.EmbeddingResponse;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

/**
 * Service responsible for managing the document corpus and embeddings.
 */
@Service
public class DocumentService {

    private static final Logger logger = LoggerFactory.getLogger(DocumentService.class);

    private final EmbeddingModel embeddingModel;
    private final InMemoryVectorStore vectorStore;

    // Hardcoded sample documents
    private static final List<Document> SAMPLE_DOCUMENTS = List.of(
            new Document(
                    "doc-1",
                    "Spring AI is a framework for building AI-powered applications using Spring Boot. " +
                            "It provides abstractions for working with Large Language Models (LLMs), " +
                            "embeddings, and vector stores. Spring AI supports multiple AI providers " +
                            "including OpenAI, Azure OpenAI, Hugging Face, and others through a unified API."),
            new Document(
                    "doc-2",
                    "Retrieval-Augmented Generation (RAG) is an AI pattern that combines information retrieval " +
                            "with generative AI. Instead of relying solely on the LLM's training data, RAG retrieves " +
                            "relevant documents from a knowledge base and uses them as context for generating answers. "
                            +
                            "This approach reduces hallucination and enables answers based on current, specific information."),
            new Document(
                    "doc-3",
                    "Vector embeddings are numerical representations of text that capture semantic meaning. " +
                            "Similar texts have similar vector representations, enabling semantic search through " +
                            "mathematical operations like cosine similarity. Embeddings are typically generated by " +
                            "neural networks trained on large text corpora and have dimensions ranging from hundreds " +
                            "to thousands of values."));

    public DocumentService(EmbeddingModel embeddingModel, InMemoryVectorStore vectorStore) {
        this.embeddingModel = embeddingModel;
        this.vectorStore = vectorStore;
    }

    /**
     * Initialize the document store with sample documents on application startup.
     */
    @PostConstruct
    public void initialize() {
        logger.info("Initializing document corpus with {} documents", SAMPLE_DOCUMENTS.size());
        embedAndStoreDocuments(SAMPLE_DOCUMENTS);
        logger.info("Document initialization complete. Vector store contains {} documents",
                vectorStore.size());
    }

    /**
     * Generate embeddings for documents and store them in the vector store.
     */
    private void embedAndStoreDocuments(List<Document> documents) {
        for (Document doc : documents) {
            try {
                logger.debug("Generating embedding for document: {}", doc.getId());

                // Generate embedding using Spring AI
                EmbeddingResponse response = embeddingModel.embedForResponse(List.of(doc.getContent()));
                float[] rawEmbedding = response.getResults().get(0).getOutput();

                // Convert float[] to List<Double>
                List<Double> embedding = new ArrayList<>(rawEmbedding.length);
                for (float value : rawEmbedding) {
                    embedding.add((double) value);
                }

                // Set embedding and store
                doc.setEmbedding(embedding);
                vectorStore.addDocument(doc);

                logger.debug("Successfully embedded and stored document: {}", doc.getId());
            } catch (Exception e) {
                logger.error("Failed to embed document {}: {}", doc.getId(), e.getMessage(), e);
                throw new RuntimeException("Failed to initialize document embeddings", e);
            }
        }
    }

    /**
     * Get all sample documents (for testing/debugging).
     */
    public List<Document> getSampleDocuments() {
        return SAMPLE_DOCUMENTS;
    }
}
